# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lfwcfVzLYm1JKvFuoCzF6XFXCvZstej7A/TzMdSJeHMvSsgSg+oiuKtUoengJLF0pifRKjQMQCXPudQgX6tpAwYt+tdoQoGr05aWAdYwwHErO2x3qbeRN55XGy/rNZx67OaAhpMiMZitm3jTAouCKMPjKVYAdBo5CI0K4NmQpd6nphvngoRQ/yXGe5bewpsGdLvfgdCc+yJdriOtkYq4KGBoZ8pqVHpXsHJjsaC4XtE+5dIrzcdTXsa2oS3FN3p/zeNBgDzQTC1W8xMhAoGMvOXxCBx/iyhYESqHAiyEDDYC6mobTKx1Aa/m80/Z0ovlTJA9nBXZjJR3ZLKyQofpPqIg7W8vrNDFpcRog/vn+WB5NvPoLDYgi0n3jbTYwRqxli05KzTJD6t6u/2MqyrnQUEZU5AcIsz0wdzPaPx4B2yKxKbSaqADxAXg7B7L+7jA0DK775abOZRmlkMRirQud/u9z5XlE5ST+YRutpzh+dJ0+V04cGglXYNCChu/vNlvPfIJ5uqCvqmNpRlFfEvD51UyDRQ9LL2mtxSyu8ZwohgViuur+/cfq4XzzdA9ahV72U1C+JoabAN9DwCtJTOYZdF6MvqWKa3uR8y4Eau1Ma3SsLOfZ/K1ngC9lSj9WtpGFxbTQp4GivQgsPKkijmgN0QOTeghclQlvqHWylkKXnI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml