travis:
  secure:
    BINSTAR_TOKEN: lfwcfVzLYm1JKvFuoCzF6XFXCvZstej7A/TzMdSJeHMvSsgSg+oiuKtUoengJLF0pifRKjQMQCXPudQgX6tpAwYt+tdoQoGr05aWAdYwwHErO2x3qbeRN55XGy/rNZx67OaAhpMiMZitm3jTAouCKMPjKVYAdBo5CI0K4NmQpd6nphvngoRQ/yXGe5bewpsGdLvfgdCc+yJdriOtkYq4KGBoZ8pqVHpXsHJjsaC4XtE+5dIrzcdTXsa2oS3FN3p/zeNBgDzQTC1W8xMhAoGMvOXxCBx/iyhYESqHAiyEDDYC6mobTKx1Aa/m80/Z0ovlTJA9nBXZjJR3ZLKyQofpPqIg7W8vrNDFpcRog/vn+WB5NvPoLDYgi0n3jbTYwRqxli05KzTJD6t6u/2MqyrnQUEZU5AcIsz0wdzPaPx4B2yKxKbSaqADxAXg7B7L+7jA0DK775abOZRmlkMRirQud/u9z5XlE5ST+YRutpzh+dJ0+V04cGglXYNCChu/vNlvPfIJ5uqCvqmNpRlFfEvD51UyDRQ9LL2mtxSyu8ZwohgViuur+/cfq4XzzdA9ahV72U1C+JoabAN9DwCtJTOYZdF6MvqWKa3uR8y4Eau1Ma3SsLOfZ/K1ngC9lSj9WtpGFxbTQp4GivQgsPKkijmgN0QOTeghclQlvqHWylkKXnI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
