travis:
  secure:
    BINSTAR_TOKEN: Q2nNy0J2qMt0ZLUz8z+y7alhmxUJavvZvX4GL4ebasl0WspSfTprMwua7uNICDvtZIApFc6AO1wE36ykin3yAaS9xQ55lgfIMhPUHQvSC94DztJRgmyVC5TczYFVO6NWAmqwrwMlf78f0ydhTpcvlFjqfsF5/fHzPsIPP+qpup5vUMFTPhla0INxRSDRCYhchYXoBQJfi4B/ftNO4q+RNp5O1hpebaR+dRD1x65GYfOgwfTsvSZ87ELTz9Yg+e0qejvLrzexyP1dJRka0YfWNgbgenaE5pSJa4rcNrG/4Evc6H21vFqomDtS2oEiPlVAJq9cB/uDtL37nx5zsx7lKH4B+X9rn84htMjUvc90LNXwUUlP9JZNs+jwJOxivMueJqLWj9mlYpUny/Dk4Z+XrL5H3D6WnWbxODLhfZK2RhqSkZg7jqtbK83wdTbDJkuiA5vIpIoBUlVt/KdRwq0eANo2Yr2+L1HN/eyZT5g9I6GK38V82oBNQNHfI4QMEJt5j8ogSXKh5jKqr6Mebqfjn8JlJJVAfR+HN/vpT7iMqq7KHiI/pSXuJEd5efw1WNVl4Fw30A+tvkz4eMGzZFRXsKnfDpkASZjMc/quVK0I34enLHckRrhH6/Sn0gE63DLRN7t1ZcJWSulavwL49Ke5CVyXmNicOw3V/BA4E3FEW3c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
